watch_stylesheet: true
watch_config: true
debug: false
update_check: true 
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: false
      duration: 0
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "system"
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 28
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
      - "win_button"
      - "glazewm_workspaces"
      - "glazewm_tiling_direction"
      - "lines"
      - "taskbar"
      - "lines"      
      - "traffic"
      center:
      - "clock"
      right:
      - "media"
      - "lines"
      - "wifi"
      - "bluetooth"
      - "wallpapers"
      - "lines"
      - "microphone"
      - "volume"
      #- "brightness"
      - "notifications"
      - "lines"
      - "Battery"
      - "memory"
      - "cpu"
      - "lines"
      - "power_menu"
      - "lines"
  # secondary-bar:
  #   enabled: true
  #   screens: ["*"]
  #   class_name: "yasb-bar secondary-bar"
  #   alignment:
  #     position: "bottom"
  #     center: false
  #   blur_effect:
  #     enabled: false
  #     acrylic: false
  #     dark_mode: false
  #     round_corners: false
  #     border_color: "system"
  #   window_flags:
  #     always_on_top: false
  #     windows_app_bar: true
  #     hide_on_fullscreen: true
  #   dimensions:q
  #     width: "100%"
  #     height: 32
  #   padding:
  #     top: 0
  #     left: 0
  #     bottom: 0
  #     right: 0
  #   widgets:
  #     left:
  #     center:
  #     right:
widgets:
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist} - {title}"
      max_field_size:
        label: 10
        label_alt: 20
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: true
      hide_empty: false
      thumbnail_alpha: 100
      thumbnail_padding: 16
      thumbnail_corner_radius: 0
      thumbnail_edge_fade: true
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"
      media_menu:
        blur: false
        round_corners: false
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 4
        thumbnail_size: 100
        max_title_size: 80
        max_artist_size: 20
        show_source: true
      label_shadow:
        enabled: true
        color: "#000000"
        radius: 2
        offset: [ 1, 1 ]
      scrolling_label:
        enabled: true
        update_interval_ms: 50
        style: "left"  
        separator: " | "
        label_padding: 1
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "{win[title]}"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 12
      max_length_ellipsis: ""
      monitor_exclusive: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "|{%A, %d %B %Y %H:%M}|"
      label_alt: "|{%a, %d %b %H:%M}|"
      timezones: []
      calendar: 
        blur: false
        round_corners: false
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_calendar"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span>{level}"
      tooltip: false
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "exec cmd.exe /c start ms-settings:sound" 
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {level}"
      icons:
        normal: "\udb80\udf6c"
        muted: "\udb80\udf6d"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "exec cmd.exe /c start ms-settings:sound" 
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: true
      blur_background: true
      animation_duration: 0
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span>"
      label_alt: "<span>\uf476</span>{count}"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "toggle_label"
        on_middle: "do_nothing"
      label_shadow:
          enabled: true
          color: "black"
          radius: 3
          offset: [ 1, 1 ]
  taskbar:
      type: "yasb.taskbar.TaskbarWidget"
      options:
        icon_size: 15
        tooltip: true
        show_only_visible: true
        strict_filtering: true
        monitor_exclusive: false
        animation:
          enabled: false
        preview:
          enabled: true
          width: 230
          delay: 200
          padding: 10
          margin: 15
        title_label:
          enabled: false
          show: "always"
          min_length: 10
          max_length: 30
        ignore_apps:
          processes: []
          titles: []
          classes: []
        label_shadow:
          enabled: true
          color: "black"
          radius: 3
          offset: [ 1, 1 ]
  bluetooth:
      type: "yasb.bluetooth.BluetoothWidget"
      options:
        label: "<span>{icon}</span> "
        label_alt: "<span>{icon}</span>{device_count} "
        label_no_device: "No devices"
        label_device_separator: ","
        max_length: 10
        max_length_ellipsis: "."
        icons: 
          bluetooth_on: "\udb80\udcaf"
          bluetooth_off: "\udb80\udcb2"
          bluetooth_connected: "\udb80\udcb1"
        device_aliases:
          - name: "T5.0"
            alias: "\uf025"
        callbacks:
          on_left: "toggle_label"
          on_middle: "exec cmd.exe /c start ms-settings:bluetooth"
          on_right: "toggle_label"
        label_shadow:
          enabled: true
          color: "black"
          radius: 3
          offset: [ 1, 1 ]
  Battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}%|time: {time_remaining}"
      update_interval: 5000
      time_remaining_natural: False
      hide_unsupported: True
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: true
        blink_interval: 500
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: "\uf0e7"
        icon_critical: "\uf244"
        icon_low: "\uf243"
        icon_medium: "\uf242"
        icon_high: "\uf241"
        icon_full: "\uf240"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "\ueab4 {download_speed}|\ueab7 {upload_speed}"
      label_alt: "Download {download_speed} | Upload {upload_speed}"
      update_interval: 1000
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
      callbacks:
        on_left: "toggle_menu"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "|<span>\uf4bc</span> {virtual_mem_free}/{virtual_mem_total}|"
      label_alt: "|<span>\uf4bc</span>:{virtual_mem_percent}%|"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[percent][total]}%"
      update_interval: 2000
      cpu_thresholds:
        low: 25
        medium: 50
        high: 90
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]  
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM OFF"
      hide_empty_workspaces: true
      hide_if_offline: false
      enable_scroll_switching: true
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
      app_icons: 
        enabled_populated: false
        enabled_active: false
        size: 20
        max_icons: 3
        hide_label: false
        hide_duplicates: true
        hide_floating: false
      animation: false
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span>{ip_addr}"
      ethernet_icon: "\ueba9"
      get_exact_wifi_strength: false  # Optional. Will require location access permission if true.
      wifi_icons: [
        "\udb82\udd2e",  # Icon for 0% strength
        "\udb82\udd1f",  # Icon for 1-24% strength
        "\udb82\udd22",  # Icon for 25-49% strength
        "\udb82\udd25",  # Icon for 50-74% strength
        "\udb82\udd28"   # Icon for 75-100% strength
      ]
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        wifi_icons_secured: [
          "\ue670",
          "\ue671",
          "\ue672",
          "\ue673",
        ]
        wifi_icons_unsecured: [
          "\uec3c",
          "\uec3d",
          "\uec3e",
          "\uec3f",
        ]        
  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "\udb81\udce1"
      vertical_label: "\udb81\udce2"
      btn_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 2, 2 ]
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\Sumit Dahiya\\Downloads\\Wallpapers"
      change_automatically: false
      update_interval: 60
      animation:
        enabled: true
        type: 'fadeInOut'
        duration: 60      
      gallery:
        enabled: true
        blur: true
        image_width: 250
        image_per_page: 5
        show_buttons: true
        orientation: "portrait"
        image_spacing: 10
        lazy_load: true
        lazy_load_delay: 0
        lazy_load_fadein: 200
        image_corner_radius: 0
        enable_cache: true
  lines:
      type: "yasb.custom.CustomWidget"
      options:
        label: "\u007c"
        label_alt: "\u007c"
        class_name: "separator-widget"
        callbacks:
          on_left: "toggle_label"
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span>{percent}"
      tooltip: true
      hide_unsupported: true
      brightness_toggle_level: [0, 50, 100]
      auto_light: false
      auto_light_icon: "\udb80\udce1"
      auto_light_night_level: 35
      auto_light_night_start_time: "19:00"
      auto_light_night_end_time: "06:45"
      auto_light_day_level: 75
      brightness_icons: [
        "\udb80\udcde",  # Icon for 0-25% brightness
        "\udb80\udcdd",  # Icon for 26-50% brightness
        "\udb80\udcdf",  # Icon for 51-75% brightness
        "\udb80\udce0"   # Icon for 76-100% brightness
      ]
      brightness_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
      callbacks:
          on_left: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]     
  win_button:
        type: "yasb.custom.CustomWidget"
        options:
          label: "(◉)"
          label_alt: "(◉)"
          class_name: "system-widget"
          callbacks:
            on_left: "exec start_menu"
            on_right: "exec start_menu"
            on_middle: "exec start_menu"
